# Generated by Django 5.2.4 on 2025-07-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '__first__'),
        ('jobs', '0003_alter_jobpost_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='skill_tags',
            field=models.ManyToManyField(blank=True, related_name='job_posts', to='common.skill'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skills_required',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='SavedJob',
        ),
    ]
